# Generated by Django 5.2 on 2026-04-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_percentage',
            field=models.IntegerField(default=100),
        ),
    ]
