# Generated by Django 5.2 on 2025-04-27 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_court_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='image',
        ),
        migrations.CreateModel(
            name='CourtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courts/images/')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courts.court')),
            ],
        ),
    ]
