# Generated by Django 5.2 on 2025-05-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_remove_court_image_courtimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la cancha está activa o suspendida.'),
        ),
    ]
