# Generated by Django 5.2 on 2025-07-06 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_court_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='characteristics',
        ),
    ]
