# Generated by Django 5.2 on 2026-03-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0006_remove_court_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtimage',
            name='image',
        ),
        migrations.AddField(
            model_name='courtimage',
            name='image_url',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
