# Generated by Django 5.2 on 2026-03-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0007_remove_courtimage_image_courtimage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
