# Generated by Django 5.2 on 2026-03-05 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courts', to='courts.category'),
        ),
        migrations.AddField(
            model_name='court',
            name='covered',
            field=models.BooleanField(default=False, help_text='Indica si la cancha tiene cubierta.'),
        ),
    ]
