# Generated by Django 5.2 on 2026-03-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournamentmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='cover_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
