# Generated by Django 5.2 on 2026-03-19 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='tournaments.tournamentmatch'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='position_in_next_match',
            field=models.CharField(blank=True, choices=[('team1', 'Equipo 1'), ('team2', 'Equipo 2')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('open', 'Inscripciones Abiertas'), ('closed', 'Inscripciones Cerradas'), ('in_progress', 'En Juego'), ('finished', 'Finalizado')], default='open', max_length=20),
        ),
    ]
