# Generated by Django 5.2 on 2025-07-16 03:19

from django.db import migrations

CATEGORIES = ["Mixto", "Hombres", "Mujeres"]

def populate_categories(apps, schema_editor):
    MatchCategory = apps.get_model('matches', 'MatchCategory')
    for category_name in CATEGORIES:
        MatchCategory.objects.get_or_create(name=category_name)

def remove_categories(apps, schema_editor):
    MatchCategory = apps.get_model('matches', 'MatchCategory')
    MatchCategory.objects.filter(name__in=CATEGORIES).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_code=remove_categories),
    ]
