# Generated by Django 5.2 on 2026-04-14 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
        ('matches', '0002_populate_match_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmatch',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_match', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='openmatch',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pendiente de Pago'), ('OPEN', 'Abierto'), ('FULL', 'Completo'), ('CANCELLED', 'Cancelado'), ('EXPIRED', 'Expirado'), ('COMPLETED', 'Completado')], default='OPEN', max_length=20),
        ),
    ]
