# Generated by Django 5.2 on 2025-04-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='auto_renew',
            field=models.BooleanField(default=True, help_text='Indica si el plan se renueva automáticamente por defecto'),
        ),
        migrations.AddField(
            model_name='plan',
            name='benefits',
            field=models.TextField(blank=True, help_text='Lista de beneficios incluidos en el plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento (ej: 10.00 para 10%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(help_text='Duración del plan en días (ej: 30 para mensual)'),
        ),
    ]
