# Generated by Django 5.2 on 2026-03-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_gateway_data_payment_method_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('wompi', 'Wompi'), ('manual', 'Manual')], default='wompi', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, help_text='URL de checkout de Wompi', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Referencia única de pago para Wompi', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_data',
            field=models.JSONField(blank=True, help_text='Datos completos de la respuesta de Wompi', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('pse', 'PSE'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('reference', 'Pago en Efectivo (Efecty/Baloto)'), ('other', 'Otro')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='ID de transacción de Wompi', max_length=255, null=True),
        ),
    ]
