# Generated by Django 5.2 on 2026-04-09 22:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='secure_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token para verificar el estado sin estar autenticado'),
        ),
    ]
