# Generated by Django 5.2 on 2025-07-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_populate_roles_and_assign_to_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='edad',
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
