# Generated by Django 5.2 on 2026-03-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_with_google',
            field=models.BooleanField(default=False),
        ),
    ]
